---
title: "network final project"
author: "George Oberle"
date: "November 4, 2014"
output: html_document
---
```{r}
library (dplyr)
library (ggmap)
library (ggplot2)
library (igraph)
data = read.csv("~/CLIO-3/finalproject/networtest.csv")
data
```


```{r}
data_g <- graph.data.frame(data, directed = FALSE)
plot (data_g)
```

```{r}
V(data_g)
bipartite.mapping(data_g)
V(data_g)$type <- bipartite.mapping(data_g)$type
is.bipartite(data_g)
plot(data_g, layout = layout.bipartite)
title("A bipartite layout of the Columbian College network")
```

```{r}
bipartite <- bipartite.projection(data_g)
str(bipartite)
plot(bipartite$proj1)
title("Just the people in the Columbian College network")
#check with Lincoln. Not really working.

```

```{r}
plot(bipartite$proj2)
title("Just the organizations")

```

```{r}
E(bipartite$proj2)
E(bipartite$proj2)$weight

plot(bipartite$proj2, edge.width = E(bipartite$proj2)$weight)
title("Fraternal organizations weighted by shared membership")
```

```{r}
plot(bipartite$proj2, edge.width = E(bipartite$proj2)$weight,
     layout = layout.fruchterman.reingold(bipartite$proj2, 
                                          weights = E(bipartite$proj2)$weight),
     vertex.label.dist = 1)
title("Fraternal organizations weighted by shared membership")
```

